version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: travel_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: narasimhakini4@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Kini_456789
    ports:
      - "5050:80"
    depends_on:
      - db

  web:
    build: .
    container_name: dj_travel_app
    restart: always

    env_file:
      - .env

    environment:
      DJANGO_SETTINGS_MODULE: dj_travel_app.settings.prod

    command: >
      sh -c "
      python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      gunicorn dj_travel_app.wsgi:application --bind 0.0.0.0:8000 --workers 3
      "

    ports:
      - "8000:8000"

    depends_on:
      - db

    volumes:
      - .:/app                                  # Your project
      - static_volume:/app/staticfiles          # Static files
      - media_volume:/app/media                 # Media files

  nginx:
    image: nginx:stable
    container_name: travel_nginx
    restart: always
    ports:
      - "80:80"

    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - web

  db:
    image: postgres:15
    container_name: travel_db
    restart: always
    environment:
      POSTGRES_DB: dj_travel_db        # Must match your DATABASE_URL
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kini_456789
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  static_volume:
  media_volume:
